#spring:
#  cloud:
#    gateway:
#      routes:
#      # 路由到本机的9001端口上
##      - id: hello_route
##        uri: http://localhost:9001/
##        predicates:
##        - Path=/producer/**
##        filters:
##        - StripPrefix=1
##        # 集成eureka注册中心的配置示例
#      - id: hello_ribbon_route
#        uri: lb://api
#        predicates:
#        - Path=/api/**
#        filters:
#        - StripPrefix=1
#        # 路由到百度页面
#      - id: baidu_route
#        uri: http://www.baidu.com
#        predicates:
#        - Path=/baidu/**
#        filters:
#        - StripPrefix=1



#server:
#  port: 9002
#spring:
#  profiles:
#    active: rewritepath_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: rewritepath_route
#        uri: lb://api
#        predicates:
#        - Path=/interface/**
#        filters:
#        - RewritePath=/interface/(?<segment>.*), /$\{segment}
#  profiles: rewritepath_route


spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: lb://api
        predicates:
        - Path=/api/**
        filters:
        - name : Hystrix
          args :
            name : forward
#            fallbackUri: authHystrixCommand
            fallbackUri: forward:/fallback



